language: node_js
node_js:
- stable
script:
- npm install
- grunt --picDomain=$(./travisBuildPicUrl.sh) --apiDomain=$(./travisBuildApiUrl.sh) --domainName=$(./travisBuild.sh)
deploy:
- provider: s3
  access_key_id: AKIAJITA2DKMLDFZTPRA
  secret_access_key:
    secure: WxVbppno/L4tOgPd/jZeReIdP2Zl6WCaitgdDdZykEkCsXIB8x0fmFsXLfm7Qw/FQlfdg1EIxBLU3nBsPKf+8u0SJvVo3VPkYje7KjKZxNkwxoB/V7bWXFZODehDV/0SnofDG0mKnH+qc9rXmbJ4IIDVovswbQ3HgBJdcEp6c1+HfyyiTh0aPxl5Hi2/WNOsjDnBLerVWalM5pXv1R0r85w9J9X6eMwC2hePRIbu9bV7rKuLmNNBREM7M0NNdSDxAAVm4ci7Zd8DzoxJ/ygJ8eS//T1hc8MHt1yOKL298Wz45wdz+w1Rxn9Hy5yd0S81Z+ASaJJg7V4pGc0tpF1P17OPAvZT7MZTnlzMapN8PjHihbSaf40FdSiNeYJWwg6FGk5DDHIZTzxlz0ytLWqK2ohOU6ZAErC/usi3dnNWz/O8Xghw07l631NAokp2N6J/dFaaJdjlkTp1JPx6zUoqPsdPknzyCq/lXZVE8QGG4pWJ7uCJoEwW8iidujUGVxPYCkZiS6sCeSNIz2J2y6yHj0471WEmcdHPx2kUUQ35KjhU1uSoWBN9IKJZknoDTIP8xPP2uh6ru6sWS6zFXx0RVD0ip7Y+fAcfyquoFsSf+JsqRiWouuP7SmyYJzRld9Rg6J9jcghGRReBZNrT5PEQWO758nhkPXH9i65+/w0e6TQ=
  bucket: www.staging.hevnly.com
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  local_dir: build
  on:
    branch: master
- provider: s3
  access_key_id: AKIAIOPUTZ5ERUZQLGAA
  secret_access_key:
    secure: WKoDn5XLfeHJu8bL/TzedQzK+hgJSrg2SeNc/u+N2ddf/xonkj6S5rtgarUrAzbyzAiIN2m4Fm7bVMrCeAe46znHIGrjXQ9c6FNY2VybwPZ/1di1adK1qzYREPPQ5M+mna7UmPQ+LvRbxhHJBrDrOs9YgttIqcNLjztqs/+3g3TwqfH6KfRz3yFVK6ZwJQw1qJI455guQnGWksmjcV7S/g6ksOhHfOFIDZZo1D1selvVpKeVCa1kE6CrhPIk1BN1GB3NDeHJGtqLDVcZYKM0Dfeysmli3/p/WlEpFlNuQRszRVsJGyNBMxo827JZkB/l4vX6KhEjMZsZau8CU2RrjY8rrtHMcEl1Q0imdNGGP2lnmuhSLprr06d5Elcw8lV8TZaV1TgZFAbc0aIP4rpi8xLHs8RKC2mo2uaMGIdZ+PwhWfNpTg/NqeXeg4chD4uY4JB4vbACPefO0xyDtyF8dETVUh4A3Mo6afqYR+tH201sE36LXDpAyQHC6VaAF8M4loFnlFNFjCIBbkNqH07SEDhS14VIDXsmBmcs2hpfTyuBs+BgRMz3+AAKfNTD9xZrAdHTwuMOmT9MFed+2dP5IbhoEnfWxNAk+VwCs8wCVmNKBy5/ncrp6Wf4Y4u9PGrdyM0K6wN3uKKi+veQQRyeuPNUY1BN/x5UhcPj6GEe7n4=
  bucket: www.hevnly.com
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  local_dir: build
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: JF2qZa/kV3aORAaPueHB39w8MEGp2tjVUJ2iKjYjEqL6lDdANqsibBT2ajj0Mo+iFNF/QFN4SZxar0j8tSvg+r4UfwROP4tZHqG1Grf2EUTYLdedTgPwKJtE+rbROxHG7pW0N1A8eCftELaZP5O49YvWyoIWAVkGnymQze2X4VkK5EC0rNgmSjB0GpX3RQRIWDlRM5oyjam8bzQ9WYtBPVTb7euoOQQ6XOOeZiO7bBpDQwS7L/WeOvcnZZVlMXWonl7gIk1qnYsuVEX4GYG/aJKotVu+hheJrFV59mdWV8vitshTPiQnzvhA4kNrnKZKTQCQr9LFNocqAFKHXK1+lK29KxfdJwlTZ1A7nI3Vp1LFmnPJ48x3uKkrcc+BqbYWf2WaF7hMVRty2XF3gX9u1qdzuioFPSs44fcLSxG1uCkPcPkuTO29jwLB3pnDO0Ywt6hzK777fN2gmH3yFp/mMGgzSNnw1NzPng4whomfnk3rKbfDWGB0jSOh/MfXZ/SOSEkP7auh0fXyHk3fsf0tqi5573LCTMzyYg/iHs+A3VlLuQdYanQAjSdPvMrINdtyLFiLL23j0RIXiayvyE4I0ycTKVbwYt4+HHrVzux+Zfd3eiTPFpLO7XddRHit1H4MM13jc7qPTagnkZpUlajLrg91G7mOnuo/s0SiByjqaLw=
