language: node_js
node_js:
- stable
script:
- npm install
- grunt --domainName=$(./travisBuild.sh)
deploy:
  provider: s3
  access_key_id: AKIAI4XWGKH4APLJJZ2A
  secret_access_key:
    secure: OZ/29MFd2UCL4yimKjD4FDsDzw6WOlOOw+cEJHwUBmPt3/Wkz8UGsiZFg5JkbEEa9MjUbBB2bD3OZyff0gZ5b1W6/X6rRT92lTRHx0BgKn5ru/YvrdMQnGEzSTVtuAcKUcQhY8CNY5LLYePDM/b2sFCPZET5Bk1onsWP+o36w5W1i5JGHZCt9nZL66VuSe8RiTzDWrlvHZJOZ7OZ6+m5OBMLG4hEP0Svb06OIO5QjmgdDzpOTQ/lyiLAjsfUHnTXODFPg9vZAJtk1qY/P2JL7owjjDYv3m8/jHPjm63Lx3ZJ9E6mtNY4PdFM0XsFGPh2OpRJgsj95KqkBoVhZqPs8WSNeKmfpD1Siwc1cgwUrfVH6aoMOomivkevJFPygjemRIti25hPKu6/ly/qraP4tsEw+26/El+0i06ra2pY8wzVjQgfmnZ5Aa9nZT3/JgeZrPRZDcQSnZYaYa/VqhEB3gs8uzBGRm65fZRi6nib5x7kvpWhURZEFW2zU9raC8jgVW1pttQFU8AyIvRAlOXn/dHDRv0tL6uY1eBY4zpGtYsOh3bYnAXF12QuRvoc9+e8m5Do2NVa5k+Ao3cW2Jy0Yq8+ktSLq61+4btKINMrBwLEX45kMdKKfLVtwPNlAoJiXsvMROETP5jUfrdkGWlXOGHx4Hfe0v7+pn/v50OXCSI=
  bucket: www.nightly.hevnly.com
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  local_dir: build
  on:
    branch: develop
